/**
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl.microserviceDSL.tests;

import com.ensias.dsl.microserviceDSL.ApplicationConfig;
import com.ensias.dsl.microserviceDSL.MicroserviceDSLFactory;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Application Config</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class ApplicationConfigTest extends ServiceConfigEntryTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(ApplicationConfigTest.class);
	}

	/**
	 * Constructs a new Application Config test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ApplicationConfigTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Application Config test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected ApplicationConfig getFixture() {
		return (ApplicationConfig)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(MicroserviceDSLFactory.eINSTANCE.createApplicationConfig());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //ApplicationConfigTest
