/**
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl.microserviceDSL.tests;

import com.ensias.dsl.microserviceDSL.MicroserviceDSLFactory;
import com.ensias.dsl.microserviceDSL.RouteConfig;

import junit.framework.TestCase;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Route Config</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class RouteConfigTest extends TestCase {

	/**
	 * The fixture for this Route Config test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RouteConfig fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(RouteConfigTest.class);
	}

	/**
	 * Constructs a new Route Config test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public RouteConfigTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Route Config test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(RouteConfig fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Route Config test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RouteConfig getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(MicroserviceDSLFactory.eINSTANCE.createRouteConfig());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //RouteConfigTest
