/**
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl.microserviceDSL.tests;

import com.ensias.dsl.microserviceDSL.MicroserviceDSLFactory;
import com.ensias.dsl.microserviceDSL.ServiceConfigEntry;

import junit.framework.TestCase;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Service Config Entry</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class ServiceConfigEntryTest extends TestCase {

	/**
	 * The fixture for this Service Config Entry test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceConfigEntry fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(ServiceConfigEntryTest.class);
	}

	/**
	 * Constructs a new Service Config Entry test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ServiceConfigEntryTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Service Config Entry test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(ServiceConfigEntry fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Service Config Entry test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceConfigEntry getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(MicroserviceDSLFactory.eINSTANCE.createServiceConfigEntry());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //ServiceConfigEntryTest
