/**
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl.microserviceDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Application Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ensias.dsl.microserviceDSL.ApplicationConfig#getAppName <em>App Name</em>}</li>
 *   <li>{@link com.ensias.dsl.microserviceDSL.ApplicationConfig#getProfile <em>Profile</em>}</li>
 *   <li>{@link com.ensias.dsl.microserviceDSL.ApplicationConfig#getLoggingLevel <em>Logging Level</em>}</li>
 * </ul>
 *
 * @see com.ensias.dsl.microserviceDSL.MicroserviceDSLPackage#getApplicationConfig()
 * @model
 * @generated
 */
public interface ApplicationConfig extends ServiceConfigEntry
{
  /**
   * Returns the value of the '<em><b>App Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>App Name</em>' attribute.
   * @see #setAppName(String)
   * @see com.ensias.dsl.microserviceDSL.MicroserviceDSLPackage#getApplicationConfig_AppName()
   * @model
   * @generated
   */
  String getAppName();

  /**
   * Sets the value of the '{@link com.ensias.dsl.microserviceDSL.ApplicationConfig#getAppName <em>App Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>App Name</em>' attribute.
   * @see #getAppName()
   * @generated
   */
  void setAppName(String value);

  /**
   * Returns the value of the '<em><b>Profile</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Profile</em>' attribute.
   * @see #setProfile(String)
   * @see com.ensias.dsl.microserviceDSL.MicroserviceDSLPackage#getApplicationConfig_Profile()
   * @model
   * @generated
   */
  String getProfile();

  /**
   * Sets the value of the '{@link com.ensias.dsl.microserviceDSL.ApplicationConfig#getProfile <em>Profile</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Profile</em>' attribute.
   * @see #getProfile()
   * @generated
   */
  void setProfile(String value);

  /**
   * Returns the value of the '<em><b>Logging Level</b></em>' attribute.
   * The literals are from the enumeration {@link com.ensias.dsl.microserviceDSL.LogLevel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logging Level</em>' attribute.
   * @see com.ensias.dsl.microserviceDSL.LogLevel
   * @see #setLoggingLevel(LogLevel)
   * @see com.ensias.dsl.microserviceDSL.MicroserviceDSLPackage#getApplicationConfig_LoggingLevel()
   * @model
   * @generated
   */
  LogLevel getLoggingLevel();

  /**
   * Sets the value of the '{@link com.ensias.dsl.microserviceDSL.ApplicationConfig#getLoggingLevel <em>Logging Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logging Level</em>' attribute.
   * @see com.ensias.dsl.microserviceDSL.LogLevel
   * @see #getLoggingLevel()
   * @generated
   */
  void setLoggingLevel(LogLevel value);

} // ApplicationConfig
