/**
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl.microserviceDSL;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Database Driver</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see com.ensias.dsl.microserviceDSL.MicroserviceDSLPackage#getDatabaseDriver()
 * @model
 * @generated
 */
public enum DatabaseDriver implements Enumerator
{
  /**
   * The '<em><b>MYSQL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MYSQL_VALUE
   * @generated
   * @ordered
   */
  MYSQL(0, "MYSQL", "MYSQL"),

  /**
   * The '<em><b>POSTGRESQL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #POSTGRESQL_VALUE
   * @generated
   * @ordered
   */
  POSTGRESQL(1, "POSTGRESQL", "POSTGRESQL"),

  /**
   * The '<em><b>H2</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #H2_VALUE
   * @generated
   * @ordered
   */
  H2(2, "H2", "H2");

  /**
   * The '<em><b>MYSQL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MYSQL
   * @model
   * @generated
   * @ordered
   */
  public static final int MYSQL_VALUE = 0;

  /**
   * The '<em><b>POSTGRESQL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #POSTGRESQL
   * @model
   * @generated
   * @ordered
   */
  public static final int POSTGRESQL_VALUE = 1;

  /**
   * The '<em><b>H2</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #H2
   * @model
   * @generated
   * @ordered
   */
  public static final int H2_VALUE = 2;

  /**
   * An array of all the '<em><b>Database Driver</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final DatabaseDriver[] VALUES_ARRAY =
    new DatabaseDriver[]
    {
      MYSQL,
      POSTGRESQL,
      H2,
    };

  /**
   * A public read-only list of all the '<em><b>Database Driver</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<DatabaseDriver> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Database Driver</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DatabaseDriver get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      DatabaseDriver result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Database Driver</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DatabaseDriver getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      DatabaseDriver result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Database Driver</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DatabaseDriver get(int value)
  {
    switch (value)
    {
      case MYSQL_VALUE: return MYSQL;
      case POSTGRESQL_VALUE: return POSTGRESQL;
      case H2_VALUE: return H2;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private DatabaseDriver(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //DatabaseDriver
