/**
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl.microserviceDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Database Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.ensias.dsl.microserviceDSL.DatabaseConfig#getDbUrl <em>Db Url</em>}</li>
 *   <li>{@link com.ensias.dsl.microserviceDSL.DatabaseConfig#getDbUsername <em>Db Username</em>}</li>
 *   <li>{@link com.ensias.dsl.microserviceDSL.DatabaseConfig#getDbPassword <em>Db Password</em>}</li>
 *   <li>{@link com.ensias.dsl.microserviceDSL.DatabaseConfig#getDriver <em>Driver</em>}</li>
 *   <li>{@link com.ensias.dsl.microserviceDSL.DatabaseConfig#getDdl <em>Ddl</em>}</li>
 * </ul>
 *
 * @see com.ensias.dsl.microserviceDSL.MicroserviceDSLPackage#getDatabaseConfig()
 * @model
 * @generated
 */
public interface DatabaseConfig extends ServiceConfigEntry
{
  /**
   * Returns the value of the '<em><b>Db Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Db Url</em>' attribute.
   * @see #setDbUrl(String)
   * @see com.ensias.dsl.microserviceDSL.MicroserviceDSLPackage#getDatabaseConfig_DbUrl()
   * @model
   * @generated
   */
  String getDbUrl();

  /**
   * Sets the value of the '{@link com.ensias.dsl.microserviceDSL.DatabaseConfig#getDbUrl <em>Db Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Db Url</em>' attribute.
   * @see #getDbUrl()
   * @generated
   */
  void setDbUrl(String value);

  /**
   * Returns the value of the '<em><b>Db Username</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Db Username</em>' attribute.
   * @see #setDbUsername(String)
   * @see com.ensias.dsl.microserviceDSL.MicroserviceDSLPackage#getDatabaseConfig_DbUsername()
   * @model
   * @generated
   */
  String getDbUsername();

  /**
   * Sets the value of the '{@link com.ensias.dsl.microserviceDSL.DatabaseConfig#getDbUsername <em>Db Username</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Db Username</em>' attribute.
   * @see #getDbUsername()
   * @generated
   */
  void setDbUsername(String value);

  /**
   * Returns the value of the '<em><b>Db Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Db Password</em>' attribute.
   * @see #setDbPassword(String)
   * @see com.ensias.dsl.microserviceDSL.MicroserviceDSLPackage#getDatabaseConfig_DbPassword()
   * @model
   * @generated
   */
  String getDbPassword();

  /**
   * Sets the value of the '{@link com.ensias.dsl.microserviceDSL.DatabaseConfig#getDbPassword <em>Db Password</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Db Password</em>' attribute.
   * @see #getDbPassword()
   * @generated
   */
  void setDbPassword(String value);

  /**
   * Returns the value of the '<em><b>Driver</b></em>' attribute.
   * The literals are from the enumeration {@link com.ensias.dsl.microserviceDSL.DatabaseDriver}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Driver</em>' attribute.
   * @see com.ensias.dsl.microserviceDSL.DatabaseDriver
   * @see #setDriver(DatabaseDriver)
   * @see com.ensias.dsl.microserviceDSL.MicroserviceDSLPackage#getDatabaseConfig_Driver()
   * @model
   * @generated
   */
  DatabaseDriver getDriver();

  /**
   * Sets the value of the '{@link com.ensias.dsl.microserviceDSL.DatabaseConfig#getDriver <em>Driver</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Driver</em>' attribute.
   * @see com.ensias.dsl.microserviceDSL.DatabaseDriver
   * @see #getDriver()
   * @generated
   */
  void setDriver(DatabaseDriver value);

  /**
   * Returns the value of the '<em><b>Ddl</b></em>' attribute.
   * The literals are from the enumeration {@link com.ensias.dsl.microserviceDSL.DdlType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ddl</em>' attribute.
   * @see com.ensias.dsl.microserviceDSL.DdlType
   * @see #setDdl(DdlType)
   * @see com.ensias.dsl.microserviceDSL.MicroserviceDSLPackage#getDatabaseConfig_Ddl()
   * @model
   * @generated
   */
  DdlType getDdl();

  /**
   * Sets the value of the '{@link com.ensias.dsl.microserviceDSL.DatabaseConfig#getDdl <em>Ddl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ddl</em>' attribute.
   * @see com.ensias.dsl.microserviceDSL.DdlType
   * @see #getDdl()
   * @generated
   */
  void setDdl(DdlType value);

} // DatabaseConfig
