/**
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl.microserviceDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.ensias.dsl.microserviceDSL.MicroserviceDSLPackage
 * @generated
 */
public interface MicroserviceDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MicroserviceDSLFactory eINSTANCE = com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Discovery</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Discovery</em>'.
   * @generated
   */
  Discovery createDiscovery();

  /**
   * Returns a new object of class '<em>Gateway</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Gateway</em>'.
   * @generated
   */
  Gateway createGateway();

  /**
   * Returns a new object of class '<em>Route Config</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Route Config</em>'.
   * @generated
   */
  RouteConfig createRouteConfig();

  /**
   * Returns a new object of class '<em>Config Server</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Config Server</em>'.
   * @generated
   */
  ConfigServer createConfigServer();

  /**
   * Returns a new object of class '<em>Service</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Service</em>'.
   * @generated
   */
  Service createService();

  /**
   * Returns a new object of class '<em>Service Config Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Service Config Entry</em>'.
   * @generated
   */
  ServiceConfigEntry createServiceConfigEntry();

  /**
   * Returns a new object of class '<em>Server Config</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Server Config</em>'.
   * @generated
   */
  ServerConfig createServerConfig();

  /**
   * Returns a new object of class '<em>Application Config</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Application Config</em>'.
   * @generated
   */
  ApplicationConfig createApplicationConfig();

  /**
   * Returns a new object of class '<em>Database Config</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Database Config</em>'.
   * @generated
   */
  DatabaseConfig createDatabaseConfig();

  /**
   * Returns a new object of class '<em>Actuator Config</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Actuator Config</em>'.
   * @generated
   */
  ActuatorConfig createActuatorConfig();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MicroserviceDSLPackage getMicroserviceDSLPackage();

} //MicroserviceDSLFactory
