/**
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl.microserviceDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.ensias.dsl.microserviceDSL.MicroserviceDSLFactory
 * @model kind="package"
 * @generated
 */
public interface MicroserviceDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "microserviceDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ensias.com/dsl/MicroserviceDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "microserviceDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MicroserviceDSLPackage eINSTANCE = com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link com.ensias.dsl.microserviceDSL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ensias.dsl.microserviceDSL.impl.ModelImpl
   * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Group Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__GROUP_NAME = 1;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__VERSION = 2;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DESCRIPTION = 3;

  /**
   * The feature id for the '<em><b>Discovery</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DISCOVERY = 4;

  /**
   * The feature id for the '<em><b>Config Server</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CONFIG_SERVER = 5;

  /**
   * The feature id for the '<em><b>Services</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SERVICES = 6;

  /**
   * The feature id for the '<em><b>Gateway</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__GATEWAY = 7;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link com.ensias.dsl.microserviceDSL.impl.DiscoveryImpl <em>Discovery</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ensias.dsl.microserviceDSL.impl.DiscoveryImpl
   * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getDiscovery()
   * @generated
   */
  int DISCOVERY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISCOVERY__NAME = 0;

  /**
   * The feature id for the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISCOVERY__PORT = 1;

  /**
   * The feature id for the '<em><b>Default Zone</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISCOVERY__DEFAULT_ZONE = 2;

  /**
   * The feature id for the '<em><b>Custom Deps</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISCOVERY__CUSTOM_DEPS = 3;

  /**
   * The number of structural features of the '<em>Discovery</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISCOVERY_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link com.ensias.dsl.microserviceDSL.impl.GatewayImpl <em>Gateway</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ensias.dsl.microserviceDSL.impl.GatewayImpl
   * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getGateway()
   * @generated
   */
  int GATEWAY = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GATEWAY__NAME = 0;

  /**
   * The feature id for the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GATEWAY__PORT = 1;

  /**
   * The feature id for the '<em><b>Routes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GATEWAY__ROUTES = 2;

  /**
   * The feature id for the '<em><b>Custom Deps</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GATEWAY__CUSTOM_DEPS = 3;

  /**
   * The number of structural features of the '<em>Gateway</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GATEWAY_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link com.ensias.dsl.microserviceDSL.impl.RouteConfigImpl <em>Route Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ensias.dsl.microserviceDSL.impl.RouteConfigImpl
   * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getRouteConfig()
   * @generated
   */
  int ROUTE_CONFIG = 3;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTE_CONFIG__PATH = 0;

  /**
   * The feature id for the '<em><b>Service</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTE_CONFIG__SERVICE = 1;

  /**
   * The number of structural features of the '<em>Route Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUTE_CONFIG_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.ensias.dsl.microserviceDSL.impl.ConfigServerImpl <em>Config Server</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ensias.dsl.microserviceDSL.impl.ConfigServerImpl
   * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getConfigServer()
   * @generated
   */
  int CONFIG_SERVER = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_SERVER__NAME = 0;

  /**
   * The feature id for the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_SERVER__PORT = 1;

  /**
   * The feature id for the '<em><b>Git Uri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_SERVER__GIT_URI = 2;

  /**
   * The feature id for the '<em><b>Git Branch</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_SERVER__GIT_BRANCH = 3;

  /**
   * The feature id for the '<em><b>Custom Deps</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_SERVER__CUSTOM_DEPS = 4;

  /**
   * The number of structural features of the '<em>Config Server</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_SERVER_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link com.ensias.dsl.microserviceDSL.impl.ServiceImpl <em>Service</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ensias.dsl.microserviceDSL.impl.ServiceImpl
   * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getService()
   * @generated
   */
  int SERVICE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE__NAME = 0;

  /**
   * The feature id for the '<em><b>Dependencies</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE__DEPENDENCIES = 1;

  /**
   * The feature id for the '<em><b>Configuration</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE__CONFIGURATION = 2;

  /**
   * The number of structural features of the '<em>Service</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.ensias.dsl.microserviceDSL.impl.ServiceConfigEntryImpl <em>Service Config Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ensias.dsl.microserviceDSL.impl.ServiceConfigEntryImpl
   * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getServiceConfigEntry()
   * @generated
   */
  int SERVICE_CONFIG_ENTRY = 6;

  /**
   * The number of structural features of the '<em>Service Config Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_CONFIG_ENTRY_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.ensias.dsl.microserviceDSL.impl.ServerConfigImpl <em>Server Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ensias.dsl.microserviceDSL.impl.ServerConfigImpl
   * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getServerConfig()
   * @generated
   */
  int SERVER_CONFIG = 7;

  /**
   * The feature id for the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_CONFIG__PORT = SERVICE_CONFIG_ENTRY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Context Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_CONFIG__CONTEXT_PATH = SERVICE_CONFIG_ENTRY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Server Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_CONFIG_FEATURE_COUNT = SERVICE_CONFIG_ENTRY_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.ensias.dsl.microserviceDSL.impl.ApplicationConfigImpl <em>Application Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ensias.dsl.microserviceDSL.impl.ApplicationConfigImpl
   * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getApplicationConfig()
   * @generated
   */
  int APPLICATION_CONFIG = 8;

  /**
   * The feature id for the '<em><b>App Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_CONFIG__APP_NAME = SERVICE_CONFIG_ENTRY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Profile</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_CONFIG__PROFILE = SERVICE_CONFIG_ENTRY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Logging Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_CONFIG__LOGGING_LEVEL = SERVICE_CONFIG_ENTRY_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Application Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_CONFIG_FEATURE_COUNT = SERVICE_CONFIG_ENTRY_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.ensias.dsl.microserviceDSL.impl.DatabaseConfigImpl <em>Database Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ensias.dsl.microserviceDSL.impl.DatabaseConfigImpl
   * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getDatabaseConfig()
   * @generated
   */
  int DATABASE_CONFIG = 9;

  /**
   * The feature id for the '<em><b>Db Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATABASE_CONFIG__DB_URL = SERVICE_CONFIG_ENTRY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Db Username</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATABASE_CONFIG__DB_USERNAME = SERVICE_CONFIG_ENTRY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Db Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATABASE_CONFIG__DB_PASSWORD = SERVICE_CONFIG_ENTRY_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Driver</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATABASE_CONFIG__DRIVER = SERVICE_CONFIG_ENTRY_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Ddl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATABASE_CONFIG__DDL = SERVICE_CONFIG_ENTRY_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Database Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATABASE_CONFIG_FEATURE_COUNT = SERVICE_CONFIG_ENTRY_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link com.ensias.dsl.microserviceDSL.impl.ActuatorConfigImpl <em>Actuator Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ensias.dsl.microserviceDSL.impl.ActuatorConfigImpl
   * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getActuatorConfig()
   * @generated
   */
  int ACTUATOR_CONFIG = 10;

  /**
   * The feature id for the '<em><b>Healthcheck Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR_CONFIG__HEALTHCHECK_PATH = SERVICE_CONFIG_ENTRY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Metrics Enabled</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR_CONFIG__METRICS_ENABLED = SERVICE_CONFIG_ENTRY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Info Enabled</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR_CONFIG__INFO_ENABLED = SERVICE_CONFIG_ENTRY_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Actuator Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR_CONFIG_FEATURE_COUNT = SERVICE_CONFIG_ENTRY_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.ensias.dsl.microserviceDSL.Dependency <em>Dependency</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ensias.dsl.microserviceDSL.Dependency
   * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getDependency()
   * @generated
   */
  int DEPENDENCY = 11;

  /**
   * The meta object id for the '{@link com.ensias.dsl.microserviceDSL.DatabaseDriver <em>Database Driver</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ensias.dsl.microserviceDSL.DatabaseDriver
   * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getDatabaseDriver()
   * @generated
   */
  int DATABASE_DRIVER = 12;

  /**
   * The meta object id for the '{@link com.ensias.dsl.microserviceDSL.DdlType <em>Ddl Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ensias.dsl.microserviceDSL.DdlType
   * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getDdlType()
   * @generated
   */
  int DDL_TYPE = 13;

  /**
   * The meta object id for the '{@link com.ensias.dsl.microserviceDSL.LogLevel <em>Log Level</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.ensias.dsl.microserviceDSL.LogLevel
   * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getLogLevel()
   * @generated
   */
  int LOG_LEVEL = 14;


  /**
   * Returns the meta object for class '{@link com.ensias.dsl.microserviceDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.ensias.dsl.microserviceDSL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.ensias.dsl.microserviceDSL.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.Model#getGroupName <em>Group Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Group Name</em>'.
   * @see com.ensias.dsl.microserviceDSL.Model#getGroupName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_GroupName();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.Model#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see com.ensias.dsl.microserviceDSL.Model#getVersion()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Version();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.Model#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see com.ensias.dsl.microserviceDSL.Model#getDescription()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Description();

  /**
   * Returns the meta object for the containment reference '{@link com.ensias.dsl.microserviceDSL.Model#getDiscovery <em>Discovery</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Discovery</em>'.
   * @see com.ensias.dsl.microserviceDSL.Model#getDiscovery()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Discovery();

  /**
   * Returns the meta object for the containment reference '{@link com.ensias.dsl.microserviceDSL.Model#getConfigServer <em>Config Server</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Config Server</em>'.
   * @see com.ensias.dsl.microserviceDSL.Model#getConfigServer()
   * @see #getModel()
   * @generated
   */
  EReference getModel_ConfigServer();

  /**
   * Returns the meta object for the containment reference list '{@link com.ensias.dsl.microserviceDSL.Model#getServices <em>Services</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Services</em>'.
   * @see com.ensias.dsl.microserviceDSL.Model#getServices()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Services();

  /**
   * Returns the meta object for the containment reference '{@link com.ensias.dsl.microserviceDSL.Model#getGateway <em>Gateway</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Gateway</em>'.
   * @see com.ensias.dsl.microserviceDSL.Model#getGateway()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Gateway();

  /**
   * Returns the meta object for class '{@link com.ensias.dsl.microserviceDSL.Discovery <em>Discovery</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Discovery</em>'.
   * @see com.ensias.dsl.microserviceDSL.Discovery
   * @generated
   */
  EClass getDiscovery();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.Discovery#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.ensias.dsl.microserviceDSL.Discovery#getName()
   * @see #getDiscovery()
   * @generated
   */
  EAttribute getDiscovery_Name();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.Discovery#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port</em>'.
   * @see com.ensias.dsl.microserviceDSL.Discovery#getPort()
   * @see #getDiscovery()
   * @generated
   */
  EAttribute getDiscovery_Port();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.Discovery#getDefaultZone <em>Default Zone</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Default Zone</em>'.
   * @see com.ensias.dsl.microserviceDSL.Discovery#getDefaultZone()
   * @see #getDiscovery()
   * @generated
   */
  EAttribute getDiscovery_DefaultZone();

  /**
   * Returns the meta object for the attribute list '{@link com.ensias.dsl.microserviceDSL.Discovery#getCustomDeps <em>Custom Deps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Custom Deps</em>'.
   * @see com.ensias.dsl.microserviceDSL.Discovery#getCustomDeps()
   * @see #getDiscovery()
   * @generated
   */
  EAttribute getDiscovery_CustomDeps();

  /**
   * Returns the meta object for class '{@link com.ensias.dsl.microserviceDSL.Gateway <em>Gateway</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Gateway</em>'.
   * @see com.ensias.dsl.microserviceDSL.Gateway
   * @generated
   */
  EClass getGateway();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.Gateway#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.ensias.dsl.microserviceDSL.Gateway#getName()
   * @see #getGateway()
   * @generated
   */
  EAttribute getGateway_Name();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.Gateway#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port</em>'.
   * @see com.ensias.dsl.microserviceDSL.Gateway#getPort()
   * @see #getGateway()
   * @generated
   */
  EAttribute getGateway_Port();

  /**
   * Returns the meta object for the containment reference list '{@link com.ensias.dsl.microserviceDSL.Gateway#getRoutes <em>Routes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Routes</em>'.
   * @see com.ensias.dsl.microserviceDSL.Gateway#getRoutes()
   * @see #getGateway()
   * @generated
   */
  EReference getGateway_Routes();

  /**
   * Returns the meta object for the attribute list '{@link com.ensias.dsl.microserviceDSL.Gateway#getCustomDeps <em>Custom Deps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Custom Deps</em>'.
   * @see com.ensias.dsl.microserviceDSL.Gateway#getCustomDeps()
   * @see #getGateway()
   * @generated
   */
  EAttribute getGateway_CustomDeps();

  /**
   * Returns the meta object for class '{@link com.ensias.dsl.microserviceDSL.RouteConfig <em>Route Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Route Config</em>'.
   * @see com.ensias.dsl.microserviceDSL.RouteConfig
   * @generated
   */
  EClass getRouteConfig();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.RouteConfig#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see com.ensias.dsl.microserviceDSL.RouteConfig#getPath()
   * @see #getRouteConfig()
   * @generated
   */
  EAttribute getRouteConfig_Path();

  /**
   * Returns the meta object for the reference '{@link com.ensias.dsl.microserviceDSL.RouteConfig#getService <em>Service</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Service</em>'.
   * @see com.ensias.dsl.microserviceDSL.RouteConfig#getService()
   * @see #getRouteConfig()
   * @generated
   */
  EReference getRouteConfig_Service();

  /**
   * Returns the meta object for class '{@link com.ensias.dsl.microserviceDSL.ConfigServer <em>Config Server</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Config Server</em>'.
   * @see com.ensias.dsl.microserviceDSL.ConfigServer
   * @generated
   */
  EClass getConfigServer();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.ConfigServer#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.ensias.dsl.microserviceDSL.ConfigServer#getName()
   * @see #getConfigServer()
   * @generated
   */
  EAttribute getConfigServer_Name();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.ConfigServer#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port</em>'.
   * @see com.ensias.dsl.microserviceDSL.ConfigServer#getPort()
   * @see #getConfigServer()
   * @generated
   */
  EAttribute getConfigServer_Port();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.ConfigServer#getGitUri <em>Git Uri</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Git Uri</em>'.
   * @see com.ensias.dsl.microserviceDSL.ConfigServer#getGitUri()
   * @see #getConfigServer()
   * @generated
   */
  EAttribute getConfigServer_GitUri();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.ConfigServer#getGitBranch <em>Git Branch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Git Branch</em>'.
   * @see com.ensias.dsl.microserviceDSL.ConfigServer#getGitBranch()
   * @see #getConfigServer()
   * @generated
   */
  EAttribute getConfigServer_GitBranch();

  /**
   * Returns the meta object for the attribute list '{@link com.ensias.dsl.microserviceDSL.ConfigServer#getCustomDeps <em>Custom Deps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Custom Deps</em>'.
   * @see com.ensias.dsl.microserviceDSL.ConfigServer#getCustomDeps()
   * @see #getConfigServer()
   * @generated
   */
  EAttribute getConfigServer_CustomDeps();

  /**
   * Returns the meta object for class '{@link com.ensias.dsl.microserviceDSL.Service <em>Service</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Service</em>'.
   * @see com.ensias.dsl.microserviceDSL.Service
   * @generated
   */
  EClass getService();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.Service#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.ensias.dsl.microserviceDSL.Service#getName()
   * @see #getService()
   * @generated
   */
  EAttribute getService_Name();

  /**
   * Returns the meta object for the attribute list '{@link com.ensias.dsl.microserviceDSL.Service#getDependencies <em>Dependencies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Dependencies</em>'.
   * @see com.ensias.dsl.microserviceDSL.Service#getDependencies()
   * @see #getService()
   * @generated
   */
  EAttribute getService_Dependencies();

  /**
   * Returns the meta object for the containment reference list '{@link com.ensias.dsl.microserviceDSL.Service#getConfiguration <em>Configuration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Configuration</em>'.
   * @see com.ensias.dsl.microserviceDSL.Service#getConfiguration()
   * @see #getService()
   * @generated
   */
  EReference getService_Configuration();

  /**
   * Returns the meta object for class '{@link com.ensias.dsl.microserviceDSL.ServiceConfigEntry <em>Service Config Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Service Config Entry</em>'.
   * @see com.ensias.dsl.microserviceDSL.ServiceConfigEntry
   * @generated
   */
  EClass getServiceConfigEntry();

  /**
   * Returns the meta object for class '{@link com.ensias.dsl.microserviceDSL.ServerConfig <em>Server Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Server Config</em>'.
   * @see com.ensias.dsl.microserviceDSL.ServerConfig
   * @generated
   */
  EClass getServerConfig();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.ServerConfig#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port</em>'.
   * @see com.ensias.dsl.microserviceDSL.ServerConfig#getPort()
   * @see #getServerConfig()
   * @generated
   */
  EAttribute getServerConfig_Port();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.ServerConfig#getContextPath <em>Context Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Context Path</em>'.
   * @see com.ensias.dsl.microserviceDSL.ServerConfig#getContextPath()
   * @see #getServerConfig()
   * @generated
   */
  EAttribute getServerConfig_ContextPath();

  /**
   * Returns the meta object for class '{@link com.ensias.dsl.microserviceDSL.ApplicationConfig <em>Application Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Application Config</em>'.
   * @see com.ensias.dsl.microserviceDSL.ApplicationConfig
   * @generated
   */
  EClass getApplicationConfig();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.ApplicationConfig#getAppName <em>App Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>App Name</em>'.
   * @see com.ensias.dsl.microserviceDSL.ApplicationConfig#getAppName()
   * @see #getApplicationConfig()
   * @generated
   */
  EAttribute getApplicationConfig_AppName();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.ApplicationConfig#getProfile <em>Profile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Profile</em>'.
   * @see com.ensias.dsl.microserviceDSL.ApplicationConfig#getProfile()
   * @see #getApplicationConfig()
   * @generated
   */
  EAttribute getApplicationConfig_Profile();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.ApplicationConfig#getLoggingLevel <em>Logging Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Logging Level</em>'.
   * @see com.ensias.dsl.microserviceDSL.ApplicationConfig#getLoggingLevel()
   * @see #getApplicationConfig()
   * @generated
   */
  EAttribute getApplicationConfig_LoggingLevel();

  /**
   * Returns the meta object for class '{@link com.ensias.dsl.microserviceDSL.DatabaseConfig <em>Database Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Database Config</em>'.
   * @see com.ensias.dsl.microserviceDSL.DatabaseConfig
   * @generated
   */
  EClass getDatabaseConfig();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.DatabaseConfig#getDbUrl <em>Db Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Db Url</em>'.
   * @see com.ensias.dsl.microserviceDSL.DatabaseConfig#getDbUrl()
   * @see #getDatabaseConfig()
   * @generated
   */
  EAttribute getDatabaseConfig_DbUrl();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.DatabaseConfig#getDbUsername <em>Db Username</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Db Username</em>'.
   * @see com.ensias.dsl.microserviceDSL.DatabaseConfig#getDbUsername()
   * @see #getDatabaseConfig()
   * @generated
   */
  EAttribute getDatabaseConfig_DbUsername();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.DatabaseConfig#getDbPassword <em>Db Password</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Db Password</em>'.
   * @see com.ensias.dsl.microserviceDSL.DatabaseConfig#getDbPassword()
   * @see #getDatabaseConfig()
   * @generated
   */
  EAttribute getDatabaseConfig_DbPassword();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.DatabaseConfig#getDriver <em>Driver</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Driver</em>'.
   * @see com.ensias.dsl.microserviceDSL.DatabaseConfig#getDriver()
   * @see #getDatabaseConfig()
   * @generated
   */
  EAttribute getDatabaseConfig_Driver();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.DatabaseConfig#getDdl <em>Ddl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ddl</em>'.
   * @see com.ensias.dsl.microserviceDSL.DatabaseConfig#getDdl()
   * @see #getDatabaseConfig()
   * @generated
   */
  EAttribute getDatabaseConfig_Ddl();

  /**
   * Returns the meta object for class '{@link com.ensias.dsl.microserviceDSL.ActuatorConfig <em>Actuator Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actuator Config</em>'.
   * @see com.ensias.dsl.microserviceDSL.ActuatorConfig
   * @generated
   */
  EClass getActuatorConfig();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.ActuatorConfig#getHealthcheckPath <em>Healthcheck Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Healthcheck Path</em>'.
   * @see com.ensias.dsl.microserviceDSL.ActuatorConfig#getHealthcheckPath()
   * @see #getActuatorConfig()
   * @generated
   */
  EAttribute getActuatorConfig_HealthcheckPath();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.ActuatorConfig#getMetricsEnabled <em>Metrics Enabled</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Metrics Enabled</em>'.
   * @see com.ensias.dsl.microserviceDSL.ActuatorConfig#getMetricsEnabled()
   * @see #getActuatorConfig()
   * @generated
   */
  EAttribute getActuatorConfig_MetricsEnabled();

  /**
   * Returns the meta object for the attribute '{@link com.ensias.dsl.microserviceDSL.ActuatorConfig#getInfoEnabled <em>Info Enabled</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Info Enabled</em>'.
   * @see com.ensias.dsl.microserviceDSL.ActuatorConfig#getInfoEnabled()
   * @see #getActuatorConfig()
   * @generated
   */
  EAttribute getActuatorConfig_InfoEnabled();

  /**
   * Returns the meta object for enum '{@link com.ensias.dsl.microserviceDSL.Dependency <em>Dependency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Dependency</em>'.
   * @see com.ensias.dsl.microserviceDSL.Dependency
   * @generated
   */
  EEnum getDependency();

  /**
   * Returns the meta object for enum '{@link com.ensias.dsl.microserviceDSL.DatabaseDriver <em>Database Driver</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Database Driver</em>'.
   * @see com.ensias.dsl.microserviceDSL.DatabaseDriver
   * @generated
   */
  EEnum getDatabaseDriver();

  /**
   * Returns the meta object for enum '{@link com.ensias.dsl.microserviceDSL.DdlType <em>Ddl Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Ddl Type</em>'.
   * @see com.ensias.dsl.microserviceDSL.DdlType
   * @generated
   */
  EEnum getDdlType();

  /**
   * Returns the meta object for enum '{@link com.ensias.dsl.microserviceDSL.LogLevel <em>Log Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Log Level</em>'.
   * @see com.ensias.dsl.microserviceDSL.LogLevel
   * @generated
   */
  EEnum getLogLevel();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MicroserviceDSLFactory getMicroserviceDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.ensias.dsl.microserviceDSL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ensias.dsl.microserviceDSL.impl.ModelImpl
     * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Group Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__GROUP_NAME = eINSTANCE.getModel_GroupName();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__VERSION = eINSTANCE.getModel_Version();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__DESCRIPTION = eINSTANCE.getModel_Description();

    /**
     * The meta object literal for the '<em><b>Discovery</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DISCOVERY = eINSTANCE.getModel_Discovery();

    /**
     * The meta object literal for the '<em><b>Config Server</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CONFIG_SERVER = eINSTANCE.getModel_ConfigServer();

    /**
     * The meta object literal for the '<em><b>Services</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SERVICES = eINSTANCE.getModel_Services();

    /**
     * The meta object literal for the '<em><b>Gateway</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__GATEWAY = eINSTANCE.getModel_Gateway();

    /**
     * The meta object literal for the '{@link com.ensias.dsl.microserviceDSL.impl.DiscoveryImpl <em>Discovery</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ensias.dsl.microserviceDSL.impl.DiscoveryImpl
     * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getDiscovery()
     * @generated
     */
    EClass DISCOVERY = eINSTANCE.getDiscovery();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISCOVERY__NAME = eINSTANCE.getDiscovery_Name();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISCOVERY__PORT = eINSTANCE.getDiscovery_Port();

    /**
     * The meta object literal for the '<em><b>Default Zone</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISCOVERY__DEFAULT_ZONE = eINSTANCE.getDiscovery_DefaultZone();

    /**
     * The meta object literal for the '<em><b>Custom Deps</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISCOVERY__CUSTOM_DEPS = eINSTANCE.getDiscovery_CustomDeps();

    /**
     * The meta object literal for the '{@link com.ensias.dsl.microserviceDSL.impl.GatewayImpl <em>Gateway</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ensias.dsl.microserviceDSL.impl.GatewayImpl
     * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getGateway()
     * @generated
     */
    EClass GATEWAY = eINSTANCE.getGateway();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GATEWAY__NAME = eINSTANCE.getGateway_Name();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GATEWAY__PORT = eINSTANCE.getGateway_Port();

    /**
     * The meta object literal for the '<em><b>Routes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GATEWAY__ROUTES = eINSTANCE.getGateway_Routes();

    /**
     * The meta object literal for the '<em><b>Custom Deps</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GATEWAY__CUSTOM_DEPS = eINSTANCE.getGateway_CustomDeps();

    /**
     * The meta object literal for the '{@link com.ensias.dsl.microserviceDSL.impl.RouteConfigImpl <em>Route Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ensias.dsl.microserviceDSL.impl.RouteConfigImpl
     * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getRouteConfig()
     * @generated
     */
    EClass ROUTE_CONFIG = eINSTANCE.getRouteConfig();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROUTE_CONFIG__PATH = eINSTANCE.getRouteConfig_Path();

    /**
     * The meta object literal for the '<em><b>Service</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROUTE_CONFIG__SERVICE = eINSTANCE.getRouteConfig_Service();

    /**
     * The meta object literal for the '{@link com.ensias.dsl.microserviceDSL.impl.ConfigServerImpl <em>Config Server</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ensias.dsl.microserviceDSL.impl.ConfigServerImpl
     * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getConfigServer()
     * @generated
     */
    EClass CONFIG_SERVER = eINSTANCE.getConfigServer();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIG_SERVER__NAME = eINSTANCE.getConfigServer_Name();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIG_SERVER__PORT = eINSTANCE.getConfigServer_Port();

    /**
     * The meta object literal for the '<em><b>Git Uri</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIG_SERVER__GIT_URI = eINSTANCE.getConfigServer_GitUri();

    /**
     * The meta object literal for the '<em><b>Git Branch</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIG_SERVER__GIT_BRANCH = eINSTANCE.getConfigServer_GitBranch();

    /**
     * The meta object literal for the '<em><b>Custom Deps</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIG_SERVER__CUSTOM_DEPS = eINSTANCE.getConfigServer_CustomDeps();

    /**
     * The meta object literal for the '{@link com.ensias.dsl.microserviceDSL.impl.ServiceImpl <em>Service</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ensias.dsl.microserviceDSL.impl.ServiceImpl
     * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getService()
     * @generated
     */
    EClass SERVICE = eINSTANCE.getService();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVICE__NAME = eINSTANCE.getService_Name();

    /**
     * The meta object literal for the '<em><b>Dependencies</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVICE__DEPENDENCIES = eINSTANCE.getService_Dependencies();

    /**
     * The meta object literal for the '<em><b>Configuration</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVICE__CONFIGURATION = eINSTANCE.getService_Configuration();

    /**
     * The meta object literal for the '{@link com.ensias.dsl.microserviceDSL.impl.ServiceConfigEntryImpl <em>Service Config Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ensias.dsl.microserviceDSL.impl.ServiceConfigEntryImpl
     * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getServiceConfigEntry()
     * @generated
     */
    EClass SERVICE_CONFIG_ENTRY = eINSTANCE.getServiceConfigEntry();

    /**
     * The meta object literal for the '{@link com.ensias.dsl.microserviceDSL.impl.ServerConfigImpl <em>Server Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ensias.dsl.microserviceDSL.impl.ServerConfigImpl
     * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getServerConfig()
     * @generated
     */
    EClass SERVER_CONFIG = eINSTANCE.getServerConfig();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVER_CONFIG__PORT = eINSTANCE.getServerConfig_Port();

    /**
     * The meta object literal for the '<em><b>Context Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVER_CONFIG__CONTEXT_PATH = eINSTANCE.getServerConfig_ContextPath();

    /**
     * The meta object literal for the '{@link com.ensias.dsl.microserviceDSL.impl.ApplicationConfigImpl <em>Application Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ensias.dsl.microserviceDSL.impl.ApplicationConfigImpl
     * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getApplicationConfig()
     * @generated
     */
    EClass APPLICATION_CONFIG = eINSTANCE.getApplicationConfig();

    /**
     * The meta object literal for the '<em><b>App Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APPLICATION_CONFIG__APP_NAME = eINSTANCE.getApplicationConfig_AppName();

    /**
     * The meta object literal for the '<em><b>Profile</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APPLICATION_CONFIG__PROFILE = eINSTANCE.getApplicationConfig_Profile();

    /**
     * The meta object literal for the '<em><b>Logging Level</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APPLICATION_CONFIG__LOGGING_LEVEL = eINSTANCE.getApplicationConfig_LoggingLevel();

    /**
     * The meta object literal for the '{@link com.ensias.dsl.microserviceDSL.impl.DatabaseConfigImpl <em>Database Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ensias.dsl.microserviceDSL.impl.DatabaseConfigImpl
     * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getDatabaseConfig()
     * @generated
     */
    EClass DATABASE_CONFIG = eINSTANCE.getDatabaseConfig();

    /**
     * The meta object literal for the '<em><b>Db Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATABASE_CONFIG__DB_URL = eINSTANCE.getDatabaseConfig_DbUrl();

    /**
     * The meta object literal for the '<em><b>Db Username</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATABASE_CONFIG__DB_USERNAME = eINSTANCE.getDatabaseConfig_DbUsername();

    /**
     * The meta object literal for the '<em><b>Db Password</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATABASE_CONFIG__DB_PASSWORD = eINSTANCE.getDatabaseConfig_DbPassword();

    /**
     * The meta object literal for the '<em><b>Driver</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATABASE_CONFIG__DRIVER = eINSTANCE.getDatabaseConfig_Driver();

    /**
     * The meta object literal for the '<em><b>Ddl</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATABASE_CONFIG__DDL = eINSTANCE.getDatabaseConfig_Ddl();

    /**
     * The meta object literal for the '{@link com.ensias.dsl.microserviceDSL.impl.ActuatorConfigImpl <em>Actuator Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ensias.dsl.microserviceDSL.impl.ActuatorConfigImpl
     * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getActuatorConfig()
     * @generated
     */
    EClass ACTUATOR_CONFIG = eINSTANCE.getActuatorConfig();

    /**
     * The meta object literal for the '<em><b>Healthcheck Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTUATOR_CONFIG__HEALTHCHECK_PATH = eINSTANCE.getActuatorConfig_HealthcheckPath();

    /**
     * The meta object literal for the '<em><b>Metrics Enabled</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTUATOR_CONFIG__METRICS_ENABLED = eINSTANCE.getActuatorConfig_MetricsEnabled();

    /**
     * The meta object literal for the '<em><b>Info Enabled</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTUATOR_CONFIG__INFO_ENABLED = eINSTANCE.getActuatorConfig_InfoEnabled();

    /**
     * The meta object literal for the '{@link com.ensias.dsl.microserviceDSL.Dependency <em>Dependency</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ensias.dsl.microserviceDSL.Dependency
     * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getDependency()
     * @generated
     */
    EEnum DEPENDENCY = eINSTANCE.getDependency();

    /**
     * The meta object literal for the '{@link com.ensias.dsl.microserviceDSL.DatabaseDriver <em>Database Driver</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ensias.dsl.microserviceDSL.DatabaseDriver
     * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getDatabaseDriver()
     * @generated
     */
    EEnum DATABASE_DRIVER = eINSTANCE.getDatabaseDriver();

    /**
     * The meta object literal for the '{@link com.ensias.dsl.microserviceDSL.DdlType <em>Ddl Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ensias.dsl.microserviceDSL.DdlType
     * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getDdlType()
     * @generated
     */
    EEnum DDL_TYPE = eINSTANCE.getDdlType();

    /**
     * The meta object literal for the '{@link com.ensias.dsl.microserviceDSL.LogLevel <em>Log Level</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.ensias.dsl.microserviceDSL.LogLevel
     * @see com.ensias.dsl.microserviceDSL.impl.MicroserviceDSLPackageImpl#getLogLevel()
     * @generated
     */
    EEnum LOG_LEVEL = eINSTANCE.getLogLevel();

  }

} //MicroserviceDSLPackage
