/**
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl.microserviceDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Service Config Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.ensias.dsl.microserviceDSL.MicroserviceDSLPackage#getServiceConfigEntry()
 * @model
 * @generated
 */
public interface ServiceConfigEntry extends EObject
{
} // ServiceConfigEntry
