/*
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class MicroserviceDSLIdeModule extends AbstractMicroserviceDSLIdeModule {
}
