/*
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MicroserviceDSLUiModule extends AbstractMicroserviceDSLUiModule {

	public MicroserviceDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
