/*
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMicroserviceDSLScopeProvider extends DelegatingScopeProvider {
}
