/*
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMicroserviceDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.ensias.dsl.microserviceDSL.MicroserviceDSLPackage.eINSTANCE);
		return result;
	}
}
