/**
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl.microserviceDSL.impl;

import com.ensias.dsl.microserviceDSL.MicroserviceDSLPackage;
import com.ensias.dsl.microserviceDSL.ServiceConfigEntry;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Service Config Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ServiceConfigEntryImpl extends MinimalEObjectImpl.Container implements ServiceConfigEntry
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ServiceConfigEntryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MicroserviceDSLPackage.Literals.SERVICE_CONFIG_ENTRY;
  }

} //ServiceConfigEntryImpl
