/*
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl.ui.tests;

import com.ensias.dsl.ui.internal.DslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MicroserviceDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("com.ensias.dsl.MicroserviceDSL");
	}

}
