/*
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MicroserviceDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/ensias/dsl/parser/antlr/internal/InternalMicroserviceDSL.tokens");
	}
}
