/*
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl.parser.antlr;

import com.ensias.dsl.parser.antlr.internal.InternalMicroserviceDSLParser;
import com.ensias.dsl.services.MicroserviceDSLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MicroserviceDSLParser extends AbstractAntlrParser {

	@Inject
	private MicroserviceDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMicroserviceDSLParser createParser(XtextTokenStream stream) {
		return new InternalMicroserviceDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MicroserviceDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MicroserviceDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
