/*
 * generated by Xtext 2.37.0
 */
package com.ensias.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MicroserviceDSLStandaloneSetup extends MicroserviceDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new MicroserviceDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
